export interface Tese {
    id: number,
    descricaoTese: string,
    tributo: string,
    modalidade: string,
    esfera: string,
    ap_financeiro: string,
    ap_industria: string,
    ap_comercio: string,
    ap_servico: string,
    resenha_sobre_acao: string,
    memoria_calculo: string,
    percentual: number,
    stj: string,
    stf: string,
    tj: string,
    trf: string,
    carf_tit: string,
    modelo_ara: string,
    regimeTributacaoAplicavel: string,
    consolidacao: string,
    importante: string,
    nova_pergunta: string,
    validacao: string,
    sugestao_de_filtro: string,
    como_fica: string
}